name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22e05cda83c727590ebe7a0b3f53bf6490c1b1792c18f5d4b533abff77a48f52"

[versions]
fabric = "0.15.1"
minecraft = "1.20.4"
