name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db4e306625eb02b043e395011a53bf8802b6debf2bbaa72e5afabc36a670ce50"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
