name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "403f915f2fe6c6d7e954ad4d86effaa7b1f805970e9dd26da003b59699e55a8a"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
