name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21e29f68635d827ebe217673fd45643a756a4340286c9b4b2beb7fe5b8cd2b63"

[versions]
fabric = "0.15.1"
minecraft = "1.20.4"
