name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cd7938621711034afacb6568165b11552a22d26e743e177c6cd00b273237f08"

[versions]
fabric = "0.15.1"
minecraft = "1.20.4"
