name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31d16fbc2ebd6b5369d0d021db8982b5ae476971b6a1a6d822b5033ff5d378b4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
