name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15d314ed9bfe5d3e7bb227a698bf7a1409b3f62a97f8c3fda6979a7b6b2330cf"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
