name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc016698ee83fc573bbdc933dc2f8372f0630522563dcee47d6dda4e379b638d"

[versions]
fabric = "0.15.1"
minecraft = "1.20.4"
