name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc8810e42e06076b10d5afa62cdc51b8ea537a16ec30c3d5df11444fc55d83be"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
