name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbe3f36b5c19b61ec5604c166d997689c0d0acd588025d8fe55e2c594cae0e97"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
