name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfb46ed6529609463630c038e031711d792006ffc9b55fed3fc98d7902be2094"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
