name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87ba47e47ff7109104b77a97485b9d3dd59bc30b98a334095bf65279748f1842"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
