name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dccbb398630a97dcfe7d62917519c3687a1aeac18ea7f9c2deaf7a22de4de62a"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
