name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4663d639986750b9f40f3fd612c015e33b9306bbc28137b5cf65c6699906a1ef"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
