name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96385cfd4643aa3eeb63b55b6c5633a2e22d0de663304a999eaf7563d4581704"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
